export const SEARCH_FILTER = 'SEARCH_FILTER';
export const SELECT_NAV_FILTER_BY_DEPARTMENT = 'SELECT_NAV_FILTER_BY_DEPARTMENT';
export const SELECT_NAV_FILTER_BY_CATEGORY = 'SELECT_NAV_FILTER_BY_CATEGORY';
